### ISSUE TITLE
I accidentally updated too high!

### ISSUE THREAD

**Issue by skornuta** [m4xw/emuMMC#28]
I was updating my firmware and I clicked on 17.0.1 without thinking about it. But when rebooting I started to get tons of errors. Is there any way to downgrade or should I wait for an update?

**Comment by urherenow** [comment]
Wait for what to update? Everything works on 17.0.1, and your issue has nothing to do with this repo at all. You need to update Atmosphere and Hekate.

**Comment by skornuta** [comment]
So I updated both of those and I can load up into sysmmc but when trying emummc it gives me an error saying "unknown pkg1 error hOs version not supported".

**Comment by urherenow** [comment]
Again, this is the wrong repo. Please close this issue and do not reply again, even if you don't figure it out. You can find help at discord retronx or at gbatemp.

The issue is that you did NOT update both. You need to extract the entire zip files of both, and you need to let them overwrite everything. If you use a mod chip, you should also put a copy of hekate on the root of your card, and name it payload.bin. You might also need to fix your hekate_ipl.ini, but post that in one of the places I just mentioned, so someone can tell you if it's wrong, but not here.

**Comment by skornuta** [comment]
Thank you I will try that and sorry that I posted it in the wrong place.
